const nameGirl = 'To:My Duyen';
const giftUrl = 'https://www.facebook.com/groups/165460116804572';
const eventName = 'Happy 8/3 !!!';
const titleCard = 'For My Duyen';
const contentCard = '</br> Hey Mỹ Duyên, cảm ơn cậu ! </br> Thật vinh dự cho anh khi được kết thân với em. Chúng ta chưa từng gặp nhau nhưng anh rất ấn tượng về em :3 </br>Mọi thứ đã sẵn sàng cho cuộc gặp mặt sắp tới .Nhớ giữ gìn sức khỏe nhaa ! </br>Chúc em có ngày 8/3 và 320 ngày còn lại trong năm 2022 hạnh phúc và vui vẻ . </br></br> From 07.29 with luv';
const giftImage = 'myduyen.jpg';
const giftBg = 'valentines.jpg'
const base64 = '';
const giftImageBase64 = "data:image/jpg;base64, " + base64;